services:
  courseapi.api:
    image: courseapi.api
    build:
      context: .
      dockerfile: CourseAPI.Api/Dockerfile
    ports:
      - 5000:8080
      - 5001:8081
    environment:
      # seq
      #      - OTEL_EXPORTER_OTLP_ENDPOINT=http://courseapi.seq:5341/ingest/otlp
      #      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://courseapi.aspire-dashboard:18889
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
  
  course.postgres:
    image: postgres:17.2
    environment:
      POSTGRES_DB: course
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./.containers/postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  
  courseapi.seq:
    image: datalust/seq:2024.3
    environment:
      ACCEPT_EULA: "Y"
    volumes:
      - ./.containers/seq_data:/data
    ports:
      - 8080:80
      - 5341:5341
  
  courseapi.aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.0
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: true
    ports:
      - 18888:18888
      