name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  DOTNET_VERSION: "9.x"

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Course

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build CourseAPI.sln --configuration Release --no-restore

      - name: Teste
        run: dotnet test CourseAPI.sln --configuration Release --no-restore --no-build

      - name: Publish
        run: dotnet publish CourseAPI.sln --configuration Release --no-restore --no-build
